on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version:
          - "1.25"
          - "1.24"
    steps:
      - uses: actions/checkout@c2d88d3ecc89a9ef08eebf45d9637801dcee7eb5 # v5.0.0
      - name: Set up Go
        uses: actions/setup-go@c0137caad775660c0844396c52da96e560aba63d # v6.0.0
        with:
          go-version: ${{ matrix.go-version }}
      - name: Run tests
        run: |
          go test -v ./...

  bench:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-arch:
          - "amd64"
          - "386"
    steps:
      - uses: actions/checkout@c2d88d3ecc89a9ef08eebf45d9637801dcee7eb5 # v5.0.0
      - name: Set up Go
        uses: actions/setup-go@c0137caad775660c0844396c52da96e560aba63d # v6.0.0
        with:
          go-version: stable
      - name: Run benchmarks
        env:
          GOARCH: ${{ matrix.go-arch }}
        run: |
          go test -bench=. -benchmem ./...
